services:
  - type: web
    name: nostalgia-radio-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: ALLOWED_ORIGIN
        value: "*"
